networks:
  pyproject_microservices-network:
    name: ${COMPOSE_PROJECT_NAME:-default}-${NETWORK_NAME}
secrets:
  package:
    file: secrets/package.txt
  service_modelserving:
    file: secrets/service_modelserving.txt
services:
  pyproject_microservices-nginx:
    container_name: ${USER_NAME:-default}_service_nginx
    env_file: .env
    environment:
      PORT_NGINX: ${PORT_NGINX}
    image: nginx:alpine
    networks:
    - ${NETWORK_NAME}
    ports:
    - ${PORT_NGINX}:80
    restart: always
    volumes:
    - ../docs/_build/html:/usr/share/nginx/html:ro
  pyproject_microservices-modelserving:
    build:
      context: ..
      dockerfile: docker/modelserving.Dockerfile
      shm_size: 1g
    cap_add:
    - SYS_PTRACE
    container_name: ${USER_NAME:-default}_service_modelserving
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
    env_file: .env
    environment:
    - ENVIRONMENT=${ENVIRONMENT}
    - PORT_DASH=${PORT_DASH}
    - PORT_GOOGLE=${PORT_GOOGLE}
    - PORT_JUPYTER=${PORT_JUPYTER}
    - PORT_MLFLOW=${PORT_MLFLOW}
    - PORT_PROFILE=${PORT_PROFILE}
    - PORT_RAY_DASHBOARD=${PORT_RAY_DASHBOARD}
    - PORT_RAY_SERVER=${PORT_RAY_SERVER}
    image: service_modelserving
    ipc: host
    networks:
    - ${NETWORK_NAME}
    ports:
    - ${PORT_DASH}:${PORT_DASH}
    - ${PORT_GOOGLE}:${PORT_GOOGLE}
    - ${PORT_JUPYTER}:${PORT_JUPYTER}
    - ${PORT_MLFLOW}:5000
    - ${PORT_PROFILE}:${PORT_PROFILE}
    - ${PORT_RAY_DASHBOARD}:${PORT_RAY_DASHBOARD}
    - ${PORT_RAY_SERVER}:${PORT_RAY_SERVER}
    restart: always
    secrets:
    - package
    - service_modelserving
    shm_size: 24g
    tty: true
    ulimits:
      memlock: -1
    volumes:
    - ${DATA_DIR}:/usr/src/service_modelserving/data
    - ../service_modelserving:/usr/src/service_modelserving
    - ../usr_vars:/usr/src/service_modelserving/usr_vars
    - ./.env:/usr/src/service_modelserving/docker/.env
    - ./modelserving.Dockerfile:/usr/src/service_modelserving/docker/modelserving.Dockerfile
    - service_modelserving-secret:/usr/src/service_modelserving/docker/secrets
  pyproject_microservices-frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: ${USER_NAME:-default}_service_frontend
    env_file: .env
    environment:
      PORT_STREAMLIT: ${PORT_STREAMLIT}
    image: service_frontend
    networks:
    - pyproject_microservices-network
    ports:
    - $PORT_STREAMLIT:8501
    restart: always
    volumes:
    - ../service_frontend:/usr/src/service_frontend
volumes:
  service_modelserving-secret: null
